name: CI

on: push

jobs:
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: üöö Get latest code
        uses: actions/checkout@v2

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: ‚öôÔ∏è Install serve
        run: npm install -g serve

      - name: ü§ñ Run the tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          build: yarn build
          start: 'serve dist -l 8080'
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
