name: CI

on: push

jobs:
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“¦ Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: ğŸ“¦ Use .nvmrc Node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: ğŸ Install and serve
        run: yarn global add serve

      - name: ğŸ¤– Run the tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          build: yarn build
          start: 'serve dist -l 8080'
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
