name: CI
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ¯ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: ğŸ Install dependencies
        run: yarn install

      - name: ğŸ‘·ğŸ½â€â™‚ï¸ Build the site and install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: yarn build

      - name: ğŸ’¾ Store the build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error

  e2e-tests:
    name: E2E Tests
    needs: build
    env:
      CI: true
    timeout-minutes: 5
    runs-on: ubuntu-latest
    # container: cypress/browsers:node14.17.0-chrome88-ff89
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     containers: [1, 2]
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸšš Get the build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: ğŸ Install serve
        run: yarn global add serve

      - name: ğŸ¤– Run the tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          start: 'serve dist -l 8080'
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 30
          record: true
          # parallel: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
